import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { EmailRequestSchema } from '@/lib/schemas'
import { escapeHtml } from '@/lib/sanitize'
import { emailRateLimiter, getClientIdentifier, rateLimitResponse } from '@/lib/rate-limit'
import { env } from '@/lib/env'

export async function POST(request: NextRequest) {
  // Rate limiting
  const clientId = getClientIdentifier(request)
  const rateLimit = await emailRateLimiter.check(clientId)
  
  if (!rateLimit.allowed) {
    return rateLimitResponse(rateLimit.resetIn)
  }

  // Check if email is configured
  if (!env.isEmailConfigured) {
    return NextResponse.json(
      { error: 'Email service is not configured.' },
      { status: 503 }
    )
  }

  try {
    const body = await request.json()
    
    // Validate request
    const validation = EmailRequestSchema.safeParse(body)
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Invalid request', details: validation.error.message },
        { status: 400 }
      )
    }

    const { email, name, reportHtml } = validation.data
    const safeName = name ? escapeHtml(name) : 'there'

    // Create styled email HTML
    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
  <div style="text-align: center; margin-bottom: 30px;">
    <div style="display: inline-block; background: #7c9885; color: white; padding: 10px 20px; border-radius: 8px; font-weight: bold;">
      Life Strategy Planner
    </div>
  </div>
  
  <p style="color: #666;">Hi ${safeName},</p>
  <p style="color: #666;">Here is your personal strategic plan. Keep this somewhere you will see it regularly.</p>
  
  <div style="border-top: 2px solid #7c9885; margin: 30px 0; padding-top: 30px;">
    ${reportHtml}
  </div>
  
  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; color: #999; font-size: 12px;">
    <p>This plan was generated by Life Strategy Planner.</p>
    <p>Remember: Review monthly and adjust as needed. Life changes, and your plan should too.</p>
  </div>
</body>
</html>
    `

    const resend = new Resend(env.RESEND_API_KEY)
    
    const { error: sendError } = await resend.emails.send({
      from: 'Life Strategy Planner <noreply@resend.dev>',
      to: email,
      subject: 'Your Personal Strategic Plan',
      html: emailHtml,
    })

    if (sendError) {
      console.error('Resend error:', sendError)
      return NextResponse.json(
        { error: 'Failed to send email' },
        { status: 500 }
      )
    }

    return NextResponse.json({ success: true })

  } catch (error) {
    console.error('Email API error:', error)
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    )
  }
}
