'use client'

import { useState, useEffect, useRef, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { Target, ArrowLeft, Loader2, RefreshCw, Download, Printer, FileText } from 'lucide-react'

interface SavedReport {
  markdown: string
  html: string
  generatedAt: string
  mode: string
}

function markdownToHtml(md: string): string {
  let html = md
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
  
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>')
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>')
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>')
  html = html.replace(/^[-*] (.+)$/gm, '<li>$1</li>')
  html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
  html = html.replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
  html = html.replace(/\n\n/g, '</p><p>')
  html = '<p>' + html + '</p>'
  html = html.replace(/<p>\s*<\/p>/g, '')
  html = html.replace(/<p>(<h[1-3]>)/g, '$1')
  html = html.replace(/(<\/h[1-3]>)<\/p>/g, '$1')
  html = html.replace(/<p>(<ul>)/g, '$1')
  html = html.replace(/(<\/ul>)<\/p>/g, '$1')
  
  return html
}

function ReportContent() {
  const searchParams = useSearchParams()
  const mode = searchParams.get('mode') || 'quick'
  
  const [report, setReport] = useState<SavedReport | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  const reportRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    try {
      const saved = localStorage.getItem('life-strategy-report-v2')
      if (saved) {
        setReport(JSON.parse(saved))
      }
    } catch (e) {
      console.error('Failed to load report:', e)
    }
  }, [])

  const generateReport = async () => {
    setIsGenerating(true)
    setError(null)

    try {
      const savedProgress = localStorage.getItem('life-strategy-progress-v2')
      if (!savedProgress) {
        throw new Error('No assessment data found')
      }

      const progress = JSON.parse(savedProgress)

      const response = await fetch('/api/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          phases: progress.phases,
          mode: progress.mode || mode,
          resumeText: progress.resumeText,
          includeCareer: progress.includeCareer
        })
      })

      if (response.status === 429) {
        setError('Too many requests. Please wait a moment.')
        return
      }

      if (!response.ok) throw new Error('Failed to generate report')

      const data = await response.json()
      
      const newReport: SavedReport = {
        markdown: data.report,
        html: markdownToHtml(data.report),
        generatedAt: new Date().toISOString(),
        mode: progress.mode || mode
      }
      
      setReport(newReport)
      localStorage.setItem('life-strategy-report-v2', JSON.stringify(newReport))

    } catch (err) {
      console.error('Report error:', err)
      setError('Failed to generate report. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handlePrint = () => window.print()

  const handleDownload = () => {
    if (!report) return
    
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Life Strategy Plan</title>
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #333; }
    h1 { color: #2d4a53; border-bottom: 2px solid #7c9885; padding-bottom: 10px; }
    h2 { color: #4a5568; margin-top: 30px; }
    h3 { color: #5f7d69; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
  </style>
</head>
<body>
  ${report.html}
  <hr>
  <p style="color: #999; font-size: 12px; text-align: center;">
    Generated by Life Strategy Planner on ${new Date(report.generatedAt).toLocaleDateString()}
  </p>
</body>
</html>`
    
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `life-strategy-${new Date().toISOString().split('T')[0]}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-stone-50">
      {/* Header */}
      <header className="border-b border-stone-200 bg-white no-print">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-sage-400 rounded-lg flex items-center justify-center">
              <Target className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold text-stone-700">Life Strategy</span>
          </Link>
          <Link href={`/assess?mode=${mode}`} className="flex items-center gap-1 text-sm text-stone-500 hover:text-stone-700">
            <ArrowLeft className="w-4 h-4" />
            Back to Assessment
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        {/* Actions */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-8 no-print">
          <div>
            <h1 className="text-2xl font-bold text-stone-700">Your Strategic Plan</h1>
            {report && (
              <p className="text-sm text-stone-500">
                Generated {new Date(report.generatedAt).toLocaleDateString()}
                {report.mode === 'full' && ' • Full Assessment'}
              </p>
            )}
          </div>
          
          <div className="flex flex-wrap items-center gap-2">
            {report && (
              <>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-4 py-2 text-sm border border-stone-200 rounded-lg hover:bg-stone-50"
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-2 px-4 py-2 text-sm border border-stone-200 rounded-lg hover:bg-stone-50"
                >
                  <Printer className="w-4 h-4" />
                  Print
                </button>
              </>
            )}
            <button
              onClick={generateReport}
              disabled={isGenerating}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-sage-400 text-white rounded-lg hover:bg-sage-500 disabled:bg-sage-300"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="w-4 h-4" />
                  {report ? 'Regenerate' : 'Generate Report'}
                </>
              )}
            </button>
          </div>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm no-print">
            {error}
          </div>
        )}

        {!report && !isGenerating && (
          <div className="text-center py-16 bg-white rounded-2xl border border-stone-200">
            <div className="w-16 h-16 bg-stone-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-8 h-8 text-stone-400" />
            </div>
            <h2 className="text-lg font-semibold text-stone-700 mb-2">No Report Yet</h2>
            <p className="text-stone-500 mb-6 max-w-md mx-auto">
              Complete your assessment phases, then generate your personalized strategic plan.
            </p>
            <button
              onClick={generateReport}
              className="inline-flex items-center gap-2 px-6 py-3 bg-sage-400 text-white rounded-xl hover:bg-sage-500 font-medium"
            >
              Generate Report
            </button>
          </div>
        )}

        {isGenerating && (
          <div className="text-center py-16 bg-white rounded-2xl border border-stone-200">
            <Loader2 className="w-12 h-12 animate-spin text-sage-400 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-stone-700 mb-2">Creating Your Plan...</h2>
            <p className="text-stone-500">This may take a moment.</p>
          </div>
        )}

        {report && !isGenerating && (
          <div 
            ref={reportRef}
            className="report-content bg-white rounded-2xl border border-stone-200 p-8 sm:p-12 shadow-sm"
            dangerouslySetInnerHTML={{ __html: report.html }}
          />
        )}

        {/* Share with professional CTA */}
        {report && !isGenerating && (
          <div className="mt-8 p-6 bg-teal-50 rounded-xl border border-teal-100 no-print">
            <h3 className="font-semibold text-teal-800 mb-2">Share With a Professional</h3>
            <p className="text-sm text-teal-700">
              This plan becomes even more powerful when reviewed with a coach, therapist, or mentor. 
              Download or print your plan and bring it to your next session.
            </p>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="py-8 px-6 bg-stone-100 border-t border-stone-200 mt-12 no-print">
        <div className="max-w-4xl mx-auto text-center text-sm text-stone-500">
          <p>© {new Date().getFullYear()} Life Strategy Planner</p>
        </div>
      </footer>
    </div>
  )
}

export default function ReportPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen flex items-center justify-center bg-stone-50">
        <Loader2 className="w-8 h-8 animate-spin text-sage-400" />
      </div>
    }>
      <ReportContent />
    </Suspense>
  )
}
