'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { 
  Target, ArrowLeft, Download, Mail, Loader2, RefreshCw, 
  Printer, AlertCircle, CheckCircle, FileText, ChevronRight
} from 'lucide-react'
import { safeMarkdownToHtml } from '@/lib/sanitize'

interface SavedReport {
  markdown: string
  html: string
  generatedAt: string
}

export default function ReportPage() {
  const [report, setReport] = useState<SavedReport | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSendingEmail, setIsSendingEmail] = useState(false)
  const [emailSent, setEmailSent] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showEmailModal, setShowEmailModal] = useState(false)
  const [emailAddress, setEmailAddress] = useState('')
  const [emailName, setEmailName] = useState('')
  const [isExporting, setIsExporting] = useState(false)
  
  const reportRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    try {
      const savedReport = localStorage.getItem('life-strategy-report')
      if (savedReport) {
        setReport(JSON.parse(savedReport))
      }
    } catch (e) {
      console.error('Failed to load saved report:', e)
    }
  }, [])

  const generateReport = async () => {
    setIsGenerating(true)
    setError(null)

    try {
      const savedProgress = localStorage.getItem('life-strategy-progress')
      if (!savedProgress) {
        throw new Error('No assessment data found')
      }

      const progress = JSON.parse(savedProgress)
      
      const savedDocs = localStorage.getItem('life-strategy-background-docs')
      const backgroundDocs = savedDocs ? JSON.parse(savedDocs) : undefined

      const response = await fetch('/api/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          phases: progress.phases,
          backgroundDocs
        })
      })

      if (response.status === 429) {
        const data = await response.json()
        setError(`Too many requests. Please wait ${data.retryAfter || 60} seconds.`)
        return
      }

      if (!response.ok) {
        throw new Error('Failed to generate report')
      }

      const data = await response.json()
      
      const newReport: SavedReport = {
        markdown: data.report,
        html: safeMarkdownToHtml(data.report),
        generatedAt: new Date().toISOString()
      }
      
      setReport(newReport)
      localStorage.setItem('life-strategy-report', JSON.stringify(newReport))

    } catch (err) {
      console.error('Generate report error:', err)
      setError('Failed to generate report. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  const handleDownloadHtml = () => {
    if (!report) return
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Life Strategy Plan</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #333; }
    h1 { color: #2d4a53; border-bottom: 2px solid #7c9885; padding-bottom: 10px; }
    h2 { color: #4a5568; margin-top: 30px; }
    h3 { color: #5f7d69; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 30px 0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  ${report.html}
  <div class="footer">
    <p>Generated by Life Strategy Planner on ${new Date(report.generatedAt).toLocaleDateString()}</p>
  </div>
</body>
</html>`
    
    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `life-strategy-plan-${new Date().toISOString().split('T')[0]}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleDownloadPdf = async () => {
    if (!report || !reportRef.current) return
    
    setIsExporting(true)
    
    try {
      const html2pdf = (await import('html2pdf.js')).default
      
      const opt = {
        margin: [0.75, 0.75, 0.75, 0.75],
        filename: `life-strategy-plan-${new Date().toISOString().split('T')[0]}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      }
      
      await html2pdf().set(opt).from(reportRef.current).save()
    } catch (err) {
      console.error('PDF export failed:', err)
      handleDownloadHtml()
    } finally {
      setIsExporting(false)
    }
  }

  const sendEmail = async () => {
    if (!report || !emailAddress) return
    
    setIsSendingEmail(true)
    setError(null)

    try {
      const response = await fetch('/api/report/email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: emailAddress,
          name: emailName || undefined,
          reportHtml: report.html,
          reportMarkdown: report.markdown
        })
      })

      if (response.status === 429) {
        setError('Too many email requests. Please try again later.')
        return
      }

      if (!response.ok) {
        throw new Error('Failed to send email')
      }

      setEmailSent(true)
      setTimeout(() => {
        setShowEmailModal(false)
        setEmailSent(false)
        setEmailAddress('')
        setEmailName('')
      }, 2000)

    } catch (err) {
      console.error('Email error:', err)
      setError('Failed to send email. Please try again.')
    } finally {
      setIsSendingEmail(false)
    }
  }

  return (
    <div className="min-h-screen bg-stone-50">
      {/* Header - hidden in print */}
      <header className="border-b border-stone-200 bg-white no-print">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-sage-400 rounded-lg flex items-center justify-center">
              <Target className="w-5 h-5 text-white" />
            </div>
            <span className="font-semibold text-stone-700">Life Strategy</span>
            <span className="px-1.5 py-0.5 bg-amber-100 text-amber-700 text-[10px] font-medium rounded">
              BETA
            </span>
          </Link>
          <Link
            href="/assess"
            className="flex items-center gap-1 text-sm text-stone-500 hover:text-stone-700"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Assessment
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        {/* Actions Bar - hidden in print */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-8 no-print">
          <div>
            <h1 className="text-2xl font-bold text-stone-700">Your Strategic Plan</h1>
            {report && (
              <p className="text-sm text-stone-500">
                Generated {new Date(report.generatedAt).toLocaleDateString()}
              </p>
            )}
          </div>
          
          <div className="flex flex-wrap items-center gap-2">
            {report && (
              <>
                <button
                  onClick={handleDownloadPdf}
                  disabled={isExporting}
                  className="flex items-center gap-2 px-4 py-2 text-sm border border-stone-200 
                             rounded-lg hover:bg-stone-50 disabled:opacity-50"
                >
                  {isExporting ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Download className="w-4 h-4" />
                  )}
                  {isExporting ? 'Exporting...' : 'PDF'}
                </button>
                <button
                  onClick={() => setShowEmailModal(true)}
                  className="flex items-center gap-2 px-4 py-2 text-sm border border-stone-200 
                             rounded-lg hover:bg-stone-50"
                >
                  <Mail className="w-4 h-4" />
                  Email
                </button>
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-2 px-4 py-2 text-sm border border-stone-200 
                             rounded-lg hover:bg-stone-50"
                >
                  <Printer className="w-4 h-4" />
                  Print
                </button>
              </>
            )}
            <button
              onClick={generateReport}
              disabled={isGenerating}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-sage-400 text-white 
                         rounded-lg hover:bg-sage-500 disabled:bg-sage-300"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <RefreshCw className="w-4 h-4" />
                  {report ? 'Regenerate' : 'Generate Report'}
                </>
              )}
            </button>
          </div>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-red-700 no-print">
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            {error}
          </div>
        )}

        {!report && !isGenerating && (
          <div className="text-center py-16 bg-white rounded-2xl border border-stone-200">
            <div className="w-16 h-16 bg-stone-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-8 h-8 text-stone-400" />
            </div>
            <h2 className="text-lg font-semibold text-stone-700 mb-2">No Report Yet</h2>
            <p className="text-stone-500 mb-6 max-w-md mx-auto">
              Complete at least 6 phases of your assessment, then generate your personalized strategic plan.
            </p>
            <button
              onClick={generateReport}
              disabled={isGenerating}
              className="inline-flex items-center gap-2 px-6 py-3 bg-sage-400 text-white 
                         rounded-xl hover:bg-sage-500 font-medium"
            >
              Generate Report
            </button>
          </div>
        )}

        {isGenerating && (
          <div className="text-center py-16 bg-white rounded-2xl border border-stone-200">
            <Loader2 className="w-12 h-12 animate-spin text-sage-400 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-stone-700 mb-2">Creating Your Plan...</h2>
            <p className="text-stone-500">This may take a moment as we synthesize your responses.</p>
          </div>
        )}

        {report && !isGenerating && (
          <>
            <div 
              ref={reportRef}
              className="report-content bg-white rounded-2xl border border-stone-200 p-8 sm:p-12 shadow-sm"
              dangerouslySetInnerHTML={{ __html: report.html }}
            />
            
            {/* Track Goals CTA */}
            <div className="mt-8 p-6 bg-gradient-to-r from-sage-50 to-teal-50 rounded-xl border border-sage-200 no-print">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <h3 className="font-semibold text-stone-700 mb-1">Track Your Goals</h3>
                  <p className="text-sm text-stone-500">
                    Import goals from your report and track your progress over time.
                  </p>
                </div>
                <Link
                  href="/goals"
                  className="flex items-center gap-2 px-4 py-2 bg-sage-400 text-white rounded-lg 
                             hover:bg-sage-500 text-sm font-medium flex-shrink-0"
                >
                  Track Goals
                  <ChevronRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          </>
        )}
      </main>

      {/* Email Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 no-print">
          <div className="bg-white rounded-2xl w-full max-w-md p-6">
            <h2 className="text-lg font-semibold text-stone-700 mb-4">Email Your Report</h2>
            
            {emailSent ? (
              <div className="text-center py-8">
                <CheckCircle className="w-12 h-12 text-sage-500 mx-auto mb-4" />
                <p className="text-stone-700 font-medium">Email sent successfully!</p>
              </div>
            ) : (
              <>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-stone-700 mb-1">
                      Your Name <span className="text-stone-400">(optional)</span>
                    </label>
                    <input
                      type="text"
                      value={emailName}
                      onChange={(e) => setEmailName(e.target.value)}
                      placeholder="Enter your name"
                      className="w-full px-4 py-2 border border-stone-200 rounded-lg 
                                 focus:outline-none focus:border-sage-400"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-stone-700 mb-1">
                      Email Address *
                    </label>
                    <input
                      type="email"
                      value={emailAddress}
                      onChange={(e) => setEmailAddress(e.target.value)}
                      placeholder="Enter your email"
                      className="w-full px-4 py-2 border border-stone-200 rounded-lg 
                                 focus:outline-none focus:border-sage-400"
                      required
                    />
                  </div>
                </div>
                
                {error && (
                  <p className="mt-3 text-sm text-red-600">{error}</p>
                )}
                
                <div className="flex gap-3 mt-6">
                  <button
                    onClick={() => {
                      setShowEmailModal(false)
                      setError(null)
                    }}
                    className="flex-1 px-4 py-2 border border-stone-200 rounded-lg 
                               hover:bg-stone-50 text-stone-700"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={sendEmail}
                    disabled={!emailAddress || isSendingEmail}
                    className="flex-1 px-4 py-2 bg-sage-400 text-white rounded-lg 
                               hover:bg-sage-500 disabled:bg-stone-300 disabled:cursor-not-allowed
                               flex items-center justify-center gap-2"
                  >
                    {isSendingEmail ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Sending...
                      </>
                    ) : (
                      <>
                        <Mail className="w-4 h-4" />
                        Send
                      </>
                    )}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* Footer - hidden in print */}
      <footer className="py-8 px-6 border-t border-stone-200 bg-stone-100 mt-12 no-print">
        <div className="max-w-4xl mx-auto text-center text-sm text-stone-500">
          <p className="mb-2">
            Remember: Review your plan monthly and adjust as life changes.
          </p>
          <p>© {new Date().getFullYear()} Life Strategy Planner. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
