'use client'

import { useState, useEffect } from 'react'
import { useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { 
  Target, Share2, Copy, Check, Mail, Download, 
  FileText, Users, Shield, ExternalLink
} from 'lucide-react'
import { cn } from '@/lib/utils'

const REPORT_STORAGE_KEY = 'life-strategy-report-v2'

export default function SharePage() {
  const searchParams = useSearchParams()
  const [report, setReport] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [shareMethod, setShareMethod] = useState<'link' | 'email' | 'download' | null>(null)

  useEffect(() => {
    const saved = localStorage.getItem(REPORT_STORAGE_KEY)
    if (saved) {
      try {
        const parsed = JSON.parse(saved)
        setReport(parsed.content || null)
      } catch {
        setReport(null)
      }
    }
  }, [])

  const handleCopyReport = () => {
    if (report) {
      navigator.clipboard.writeText(report)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleDownload = () => {
    if (!report) return
    
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Life Strategy Plan</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #4a7c59; padding-bottom: 10px; }
    h2 { color: #2a2a2a; margin-top: 30px; }
    h3 { color: #3a3a3a; margin-top: 20px; }
    ul, ol { margin: 10px 0; }
    li { margin: 5px 0; }
    strong { color: #1a1a1a; }
    hr { border: none; border-top: 1px solid #ddd; margin: 30px 0; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
    th { background: #f5f5f5; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  ${report
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n)+/g, '<ul>$&</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/---/g, '<hr>')}
  <div class="footer">
    Generated by Life Strategy Planner | ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`
    
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `life-strategy-plan-${new Date().toISOString().split('T')[0]}.html`
    document.body.appendChild(a)
    a.click()
    URL.revokeObjectURL(url)
    document.body.removeChild(a)
  }

  const handleEmailShare = () => {
    const subject = encodeURIComponent('My Life Strategy Plan')
    const body = encodeURIComponent(`Hi,

I recently completed a life strategy assessment and wanted to share my plan with you. I'd value your perspective and support as I work toward these goals.

Here's a summary of what I discovered:

${report?.slice(0, 500)}...

[Full plan attached or available at: ${window.location.origin}/report]

I'd love to discuss this with you in our next session.

Best regards`)
    
    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-stone-50">
        <header className="border-b border-stone-200 bg-white">
          <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <div className="w-8 h-8 bg-sage-400 rounded-lg flex items-center justify-center">
                <Target className="w-4 h-4 text-white" />
              </div>
              <span className="font-semibold text-stone-700">Life Strategy</span>
            </Link>
          </div>
        </header>

        <main className="max-w-3xl mx-auto px-6 py-12 text-center">
          <div className="w-16 h-16 bg-stone-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <FileText className="w-8 h-8 text-stone-400" />
          </div>
          <h1 className="text-2xl font-bold text-stone-800 mb-3">No Report Found</h1>
          <p className="text-stone-500 mb-6">
            Complete your assessment first to generate a report you can share.
          </p>
          <Link
            href="/assess"
            className="inline-flex items-center gap-2 px-6 py-3 bg-sage-400 text-white rounded-xl font-medium hover:bg-sage-500"
          >
            Start Assessment
          </Link>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-stone-50">
      {/* Header */}
      <header className="border-b border-stone-200 bg-white">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-sage-400 rounded-lg flex items-center justify-center">
              <Target className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold text-stone-700">Life Strategy</span>
          </Link>
          <Link href="/report" className="text-sm text-sage-600 hover:underline">
            View Report
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        {/* Hero */}
        <div className="text-center mb-10">
          <div className="w-16 h-16 bg-sage-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Share2 className="w-8 h-8 text-sage-600" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-stone-800 mb-3">
            Share With a Professional
          </h1>
          <p className="text-stone-500 max-w-lg mx-auto">
            Your report becomes even more valuable when discussed with a coach, therapist, or mentor.
          </p>
        </div>

        {/* Why Share */}
        <section className="mb-10">
          <h2 className="text-lg font-semibold text-stone-800 mb-4 flex items-center gap-2">
            <Users className="w-5 h-5 text-sage-500" />
            Why Share Your Report?
          </h2>
          <div className="grid sm:grid-cols-3 gap-4">
            {[
              {
                title: 'Deeper Insights',
                desc: 'A professional can help you see patterns you might miss',
              },
              {
                title: 'Accountability',
                desc: 'Sharing creates commitment and follow-through',
              },
              {
                title: 'Better Sessions',
                desc: 'Come prepared with clarity instead of figuring it out live',
              },
            ].map((item) => (
              <div key={item.title} className="bg-white rounded-xl border border-stone-200 p-4">
                <h3 className="font-medium text-stone-800 mb-1">{item.title}</h3>
                <p className="text-sm text-stone-500">{item.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Share Methods */}
        <section className="mb-10">
          <h2 className="text-lg font-semibold text-stone-800 mb-4">
            Choose How to Share
          </h2>
          <div className="space-y-3">
            {/* Copy to Clipboard */}
            <button
              onClick={handleCopyReport}
              className={cn(
                'w-full flex items-center gap-4 p-4 rounded-xl border-2 transition-all text-left',
                copied
                  ? 'border-green-400 bg-green-50'
                  : 'border-stone-200 bg-white hover:border-sage-300'
              )}
            >
              <div className={cn(
                'w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0',
                copied ? 'bg-green-100' : 'bg-stone-100'
              )}>
                {copied ? (
                  <Check className="w-5 h-5 text-green-600" />
                ) : (
                  <Copy className="w-5 h-5 text-stone-500" />
                )}
              </div>
              <div>
                <p className="font-medium text-stone-800">
                  {copied ? 'Copied!' : 'Copy to Clipboard'}
                </p>
                <p className="text-sm text-stone-500">
                  Paste into a message, document, or portal
                </p>
              </div>
            </button>

            {/* Download */}
            <button
              onClick={handleDownload}
              className="w-full flex items-center gap-4 p-4 rounded-xl border-2 border-stone-200 bg-white hover:border-sage-300 transition-all text-left"
            >
              <div className="w-10 h-10 rounded-lg bg-stone-100 flex items-center justify-center flex-shrink-0">
                <Download className="w-5 h-5 text-stone-500" />
              </div>
              <div>
                <p className="font-medium text-stone-800">Download as File</p>
                <p className="text-sm text-stone-500">
                  Save as HTML to share or print
                </p>
              </div>
            </button>

            {/* Email */}
            <button
              onClick={handleEmailShare}
              className="w-full flex items-center gap-4 p-4 rounded-xl border-2 border-stone-200 bg-white hover:border-sage-300 transition-all text-left"
            >
              <div className="w-10 h-10 rounded-lg bg-stone-100 flex items-center justify-center flex-shrink-0">
                <Mail className="w-5 h-5 text-stone-500" />
              </div>
              <div>
                <p className="font-medium text-stone-800">Share via Email</p>
                <p className="text-sm text-stone-500">
                  Open email with pre-written message
                </p>
              </div>
            </button>
          </div>
        </section>

        {/* Privacy Note */}
        <section className="bg-stone-100 rounded-xl p-5 flex items-start gap-4">
          <Shield className="w-5 h-5 text-stone-500 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-medium text-stone-700 mb-1">Your privacy is protected</p>
            <p className="text-sm text-stone-500">
              Your report is stored only in your browser. When you share it, you're in 
              control of who sees it. We don't have access to your conversations or report.
            </p>
          </div>
        </section>

        {/* Suggested Professionals */}
        <section className="mt-10">
          <h2 className="text-lg font-semibold text-stone-800 mb-4">
            Who to Share With
          </h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              {
                title: 'Life Coach',
                desc: 'Help with accountability and action planning',
                link: 'https://www.icfcoachfederation.org/find-a-coach',
              },
              {
                title: 'Therapist',
                desc: 'Explore deeper patterns and mental health',
                link: 'https://www.psychologytoday.com/us/therapists',
              },
              {
                title: 'Career Coach',
                desc: 'Navigate job transitions and career growth',
                link: 'https://www.thecoaches.com/',
              },
              {
                title: 'Trusted Mentor',
                desc: 'Someone who knows you and can give honest feedback',
                link: null,
              },
            ].map((item) => (
              <div key={item.title} className="bg-white rounded-xl border border-stone-200 p-4">
                <h3 className="font-medium text-stone-800 mb-1">{item.title}</h3>
                <p className="text-sm text-stone-500 mb-2">{item.desc}</p>
                {item.link && (
                  <a
                    href={item.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-xs text-sage-600 hover:underline"
                  >
                    Find one <ExternalLink className="w-3 h-3" />
                  </a>
                )}
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-stone-200 bg-white mt-12">
        <div className="max-w-3xl mx-auto text-center text-sm text-stone-500">
          <p>© {new Date().getFullYear()} Life Strategy Planner</p>
        </div>
      </footer>
    </div>
  )
}
